apiVersion: v1
kind: Service
metadata:
  name: harry-fitness-service
spec:
  type: NodePort
  selector:
    app: harry-fitness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
